Update schedule.yaml

diff --git a/.github/workflows/schedule.yaml b/.github/workflows/schedule.yaml
--- a/.github/workflows/schedule.yaml
+++ b/.github/workflows/schedule.yaml
@@ -23,13 +23,20 @@ jobs:
       run: |
         python -m pip install --upgrade pip
         pip install requests python-dotenv
-
-    - name: Run fetch_members
-      run: python scripts/fetch_members.py
-      env:
-        TVFY_API_KEY: ${{ secrets.TVFY_API_KEY }}
     
     - name: Run fetch_divisions
       run: python scripts/fetch_divisions.py
       env:
         TVFY_API_KEY: ${{ secrets.TVFY_API_KEY }}
+    
+    - name: Commit changes
+      run: |
+        git config --local user.email "action@github.com"
+        git config --local user.name "GitHub Action"
+        git add data/parliament/divisions.json
+        git commit -m "Update divisions data"
+        # The step below is just to ensure that the action doesn't fail if there are no changes to commit
+        git diff --quiet && git diff --staged --quiet || (git commit -am "Automate updates"; git push)
+        
+    - name: Push changes
+      run: git push
